#!/usr/bin/env python3
"""Embeds a compiled shim ELF file as a C byte array (g_shim_blob) that
winlift's host-side code (stub_patch.c) parses at conversion time to resolve
symbols and pull in PT_LOAD segments. We embed the whole ELF file verbatim
(not an objcopy-flattened image) specifically so stub_patch.c can reuse the
real ELF program/section headers instead of needing a second, separate
layout convention."""
import sys


def main():
    in_path, out_path = sys.argv[1], sys.argv[2]
    with open(in_path, 'rb') as f:
        data = f.read()

    with open(out_path, 'w') as f:
        f.write('/* generated by tools/gen_shim_blob.py from %s - do not edit by hand */\n' % in_path)
        f.write('const unsigned char g_shim_blob[] = {\n')
        for i in range(0, len(data), 16):
            chunk = data[i:i + 16]
            f.write('    ' + ','.join(str(b) for b in chunk) + ',\n')
        f.write('};\n')
        f.write('const unsigned int g_shim_blob_size = sizeof(g_shim_blob);\n')


if __name__ == '__main__':
    main()
